---
########################################################################################################################
#
# Main task
# Documentation: https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html
#
########################################################################################################################


# EC2 VPC

      - include_tasks: ec2/vpc.yml

# EC2 Subnets

      - include_tasks: ec2/subnets.yml

# EC2 Create Security Group

      - include_tasks: ec2/securitygroup.yml

# ECS Create Cluster

      - include_tasks: ecs/cluster.yml

# ECS Taskdefinition

      - include_tasks: ecs/taskdefinition.yml

# ECS Service

      - include_tasks: ecs/service.yml

